/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as EditionsWeekRouteImport } from './routes/editions.$week'
import { Route as ApiPublicEditionsIngestRouteImport } from './routes/api/public/editions/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsWeekRoute = EditionsWeekRouteImport.update({
  id: '/editions/$week',
  path: '/editions/$week',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEditionsIngestRoute = ApiPublicEditionsIngestRouteImport.update({
  id: '/api/public/editions/ingest',
  path: '/api/public/editions/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/editions/$week': typeof EditionsWeekRoute
  '/api/public/editions/ingest': typeof ApiPublicEditionsIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/editions/$week': typeof EditionsWeekRoute
  '/api/public/editions/ingest': typeof ApiPublicEditionsIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/editions/$week': typeof EditionsWeekRoute
  '/api/public/editions/ingest': typeof ApiPublicEditionsIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/archive' | '/editions/$week' | '/api/public/editions/ingest'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archive' | '/editions/$week' | '/api/public/editions/ingest'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/editions/$week'
    | '/api/public/editions/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  EditionsWeekRoute: typeof EditionsWeekRoute
  ApiPublicEditionsIngestRoute: typeof ApiPublicEditionsIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/$week': {
      id: '/editions/$week'
      path: '/editions/$week'
      fullPath: '/editions/$week'
      preLoaderRoute: typeof EditionsWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/editions/ingest': {
      id: '/api/public/editions/ingest'
      path: '/api/public/editions/ingest'
      fullPath: '/api/public/editions/ingest'
      preLoaderRoute: typeof ApiPublicEditionsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  EditionsWeekRoute: EditionsWeekRoute,
  ApiPublicEditionsIngestRoute: ApiPublicEditionsIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
